#ifndef SYSTYPE_H
#define SYSTYPE_H
namespace ecs {

	enum TypeSystem {

		TYPEPHYSICSSYSTEM,
		TYPECONTROLSYSTEM,
		TYPETRANSFORMSYSTEM,
		TYPECOLLISIONSYSTEM,
		TYPECOLLISIONRESPONSESYSTEM,

		//render system called the last
		TYPEANIMATIONSYSTEM,
		TYPERENDERSYSTEM,
		TYPERENDERTEXTSYSTEM,
		TYPEDEBUGDRAWINGSYSTEM,
		
		TOTALTYPESYSTEM
	};
}

#endif